from __future__ import annotations

DASHBOARD_ADMIN_CONTEXT = "DASHBOARD_ADMIN_CONTEXT"
DASHBOARD_ADMIN_SOURCE_MODULE = "MODULE_03_USERS_ROLES"
LEGACY_ADMIN_CABINET_MODULE = "MODULE_16_ADMIN_CABINET"
